---
ID: "79d971b2-a7c5-4524-961a-c9b988857ae0"
Parent: "962f2c89-98f0-4007-9762-cffa76fe9da0"
Template: "64b8a6d8-260b-47c4-afe2-7f290ade48cc"
Path: /sitecore/system/Modules/RWS Translation Module/Settings
SharedFields:
- ID: "0442519e-22e1-4a77-a34e-eb4f59b6ab69"
  Hint: Culture Code Mapping
  Value: "en|en-US"
- ID: "10c40322-12cc-4f45-a597-cdd088c4c48e"
  Hint: Field IDs Ignored When Translating
  Value: 
- ID: "132d371d-bf20-44c9-9841-9993cad7db0a"
  Hint: Activated
  Value: 1
- ID: "190e821a-0867-4ca8-bc93-ddd04d043657"
  Hint: password
  Value: A4cW5dpghUvN9X4L
- ID: "259dc78c-5606-4f68-9121-7a708c424719"
  Hint: client_id
  Value: 3ZIGHVDAFIH5QELT
- ID: "3d7578e8-0d98-4aaa-8390-dde24049e8ea"
  Hint: username
  Value: sitecoretest@email.com
- ID: "442b77de-19ae-444f-9125-73866c261031"
  Hint: Template IDs Ignored When Translating
  Value: 
- ID: "a66849e7-3079-49f2-b2b4-43eb80ddc288"
  Hint: client_secret
  Value: PCDDTLAKC5JZ8INU0MOA0LKJ50OVLIRT
- ID: "b048f5e4-bfb6-4a42-bffc-2c63ac69a758"
  Hint: Extended Subitem Selection Templates
  Value: "{1C82E550-EBCD-4E5D-8ABD-D50D0809541E}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "d83a7f0a-f0da-4738-aa58-760972ba6335"
  Hint: Default Depth
  Value: 1
- ID: "dc1d7640-63f1-49ea-b22e-e733c39c74fd"
  Hint: Field IDs Ignored When Creating New Item Versions
  Value: 
- ID: "ea72ce81-55a7-4663-8db9-fe82a98cf1fc"
  Hint: Item IDs Ignored When Translating
  Value: 
- ID: "fe5d1cdf-40b3-4104-b7a5-0772c1bad6be"
  Hint: endpoint url
  Value: "https://languagecloud.sdl.com"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171009T074052Z
    - ID: "469b70bf-c424-45fa-88d7-48b0b6e1f393"
      Hint: Custom Field Types Include When Translating
      Value: "Rich Text,Text,Multi-Line Text,Single-Line Text,html,General Link,General Link with Search"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "10d22b33-9464-4f3c-9a8f-c4ba89850655"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "be9863e4-0dbc-4760-a949-df3b15e39f05"
      Hint: Translation Draft
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231108T104506Z
